jwt:
    refresh:
        token:
            exppiration: 604800000
    secret-key: ENC(ntZL1NceyFZ2AZ4SzT80xrty8ThW/MFkosMjFX6JbTYMlg3JmRFAHwrw9C/1xLcRwyQMG8KVbsKDdHtbhCsQtzdQk0UnUB4ldU1U4Onndj5YwBwP2vpbo3rK5fTZ2QhD0LFjgQMwLVi1KiPpWqQskg==)
    token:
        expiration: 86400000
server:
    port: 8081
    servlet:
        context-path: /jspace-service
spring:
    application:
        name: jspace-service
    profiles:
        active: dev
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ENC(QJWkrlKUbeukPO+Q3NL14ERvXbBUc+SnXaoRRVsZhrvejBgHhZ18pAxbPQnNyrKulcg+J5s+qcVPuBXC1SKXqzqPYgtfKRAdf39ragut60/HNTVUkOnBcH7xQ/nDIiNPfpZ6RvbBNaPLtJI9GXpxtg==)
                        client-secret: ENC(req0ylCYaOeSa+fglPlw2uUn2vTGvpxzO6ekJ2H4urJsDotuI6sLvakWIfNNuJCO8o2wIHWsRzf6mx+53JBDbQvfQmTaqjcS03aqPGF0UuQ=)
                        provider: google
                        scope: openid profile email
