init:
    admin:
        password: ENC(OiYnKeBtvO7/y8d1L3kiM3IBVNj1I+3rSo4zahW18uV/Wiw9QPOMjHWQ5Y0MDPRQ)
        username: ENC(GvJrKBbVuexsG/nQJqvm1wNZGh7OubgUT+QBgYp//w9pkaJKYUfjY9THADaNpG8u)
spring:
    data:
        web:
            pageable:
                default-page-size: 10
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ENC(lmH92MTdDenom+eBoAGj6VEywumFRB6M3TA6Fm7rrKV0ylsVolih0aNfMNZ9XJ/1rDGyipgGmNn6yxfVEj4QQg==)
        url: ENC(wcC97rYNuDiXAWx7zWPNLIbz6riCsgw1b1RIdvX9OHOMjWZERd273n1Qxbg6JSJY/gtO/j+HGsZ1FU27LjvMIqcWjF8/iAAsaVajfa0GvxZx5pddTk/viiXfMLgir5SnM8rdgULHxstoZkxPDHuoKg==)
        username: ENC(O95n6eq4nzyGMJ00gNZu5fATVym7ejHVPC+h8i8QNKW6s94PQokaH+Z6Rlfrj8go)
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: false
        show-sql: false
    mail:
        host: smtp.gmail.com
        password: ENC(s733gtymVGQ/IQtr1QV4CBCGLps3+eFtj83GZFVKLDCNhC5cf/nc1NYoyCd4RoZCxr2EzXeZw35XqXR7IqQKIA==)
        port: 587
        properties:
            mail:
                debug: false
                smtp:
                    auth: true
                    ssl:
                        protocols: TLSv1.2
                    starttls:
                        enable: true
                transport:
                    protocol: smtp
        username: ENC(SouhUt3yuDNMaACH0giGMboHpqC4RznX4aTM+0zykpyUVRg6qH0D9cXkFSkvwmjC7PKWQj8fkad8tM3iqxtqCw==)
storage:
    cloudinary:
        api:
            key: ENC(G5kcnqKag2dgeC2TkQSdA3wWBCekRvoz3rpRFu1mZSzzMY7xqd2gvVN56DsC4Hz+)
            secret:
                key: ENC(vE/Il+h56XGbIPBfzE4DscJSYBA7JDhfkun2DK2SypJNU6HpqEWMX8aDSNAj05my7VCYjsdaCBYSm9ML9+Es7g==)
        cloud:
            name: ENC(prdtE2XHZVGuXYuUY2pLgQ4hD4E8XhpG9LeSX65h0EfZBpToErHsGg+JDdO38Zzf)